import 'package:blood_app/res/localizations/app_strings.dart';
import 'package:get/get_navigation/get_navigation.dart';
class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          AppStrings.startMessage: 'Start your \nbusiness with us',
          AppStrings.retailer: 'Retailer',
          AppStrings.wholesaler: 'Wholesaler',
          AppStrings.home: 'Home',
          AppStrings.notify: 'Notify',
          AppStrings.cart: 'Cart',
          AppStrings.liked: 'Liked',
          AppStrings.account: 'Account',
          AppStrings.search: 'Search',
          AppStrings.searchHint: 'Search by product',
          AppStrings.login: 'Login',
          AppStrings.signUp: 'Sign Up',
          AppStrings.signUpAs: 'Sign Up As',
          AppStrings.forgotPassword: 'Forgot Password',
          AppStrings.email: 'Email',
          AppStrings.emailHint: 'Enter your email',
          AppStrings.password: 'Password',
          AppStrings.passwordHint: 'Enter your password',
          AppStrings.confirmPassword: 'Confirm Password',
          AppStrings.confirmPasswordHint: 'Enter your confirm password',
          AppStrings.name: 'Name',
          AppStrings.nameHint: 'Enter your name',
          AppStrings.storeName: 'Store Name',
          AppStrings.storeNameHint: 'Enter your store name',
          AppStrings.loginScreenTitle: 'Login',
          AppStrings.signUpScreenTitle: 'Sign Up',
          AppStrings.contact: 'Contact',
          AppStrings.orderHistory: 'Order History',
          AppStrings.reviews: 'Reviews',
          AppStrings.settings: 'Settings',
          AppStrings.logout: 'Logout',
          AppStrings.english: 'English',
          AppStrings.urdu: 'Urdu',
          AppStrings.pleaseEnter: 'Please enter',
          AppStrings.shouldbeAtleast6Characters:
              'should be atleast 6 characters',
          AppStrings.passwordAndConfirmPasswordShouldBeSame:
              'password and confirm password should be same',
          AppStrings.phone: 'Phone',
        },
        'ur_PK': {
          AppStrings.startMessage: 'ہمارے ساتھ اپنا کاروبار شروع کریں',
          AppStrings.retailer: 'ریٹیلر',
          AppStrings.wholesaler: 'ھولسیلر',
          AppStrings.home: 'گھر',
          AppStrings.notify: 'اطلاع دیں',
          AppStrings.cart: 'ٹوکری',
          AppStrings.liked: 'پسندیدہ',
          AppStrings.account: 'اکاؤنٹ',
          AppStrings.search: 'تلاش کریں',
          AppStrings.searchHint: 'مصنوعات کے ذریعہ تلاش کریں',
          AppStrings.login: 'لاگ ان کریں',
          AppStrings.signUp: 'سائن اپ کریں',
          AppStrings.signUpAs: 'سائن اپ کریں',
          AppStrings.email: 'ای میل',
          AppStrings.emailHint: 'اپنا ای میل درج کریں',
          AppStrings.password: 'پاس ورڈ',
          AppStrings.passwordHint: 'اپنا پاس ورڈ درج کریں',
          AppStrings.confirmPassword: 'پاس ورڈ کی تصدیق کریں',
          AppStrings.confirmPasswordHint: 'اپنا پاس ورڈ کی تصدیق کریں',
          AppStrings.name: 'نام',
          AppStrings.nameHint: 'اپنا نام درج کریں',
          AppStrings.storeName: 'اسٹور کا نام',
          AppStrings.storeNameHint: 'اپنا اسٹور کا نام درج کریں',
          AppStrings.loginScreenTitle: 'لاگ ان کریں',
          AppStrings.signUpScreenTitle: 'سائن اپ کریں',
          AppStrings.contact: 'رابطہ کریں',
          AppStrings.orderHistory: 'آرڈر کی تاریخ',
          AppStrings.reviews: 'جائزے',
          AppStrings.settings: 'ترتیبات',
          AppStrings.logout: 'لاگ آؤٹ',
          AppStrings.english: 'انگریزی',
          AppStrings.urdu: 'اردو',
          AppStrings.pleaseEnter: 'درج کریں',
          AppStrings.shouldbeAtleast6Characters: 'کم از کم 6 حروف ہونے چاہئیں',
          AppStrings.passwordAndConfirmPasswordShouldBeSame:
              'پاس ورڈ اور تصدیقی پاس ورڈ ایک جیسے ہونے چاہئیں',
          AppStrings.phone: 'فون',
        },
      };
}
